Use KakatkarAkshay forks for Saltbox dependencies

diff --git a/.github/workflows/saltbox-os.yml b/.github/workflows/saltbox-os.yml
--- a/.github/workflows/saltbox-os.yml
+++ b/.github/workflows/saltbox-os.yml
@@ -67,7 +67,7 @@ jobs:
       - name: Install sb binary
         uses: jaxxstorm/action-install-gh-release@v2.1.0
         with:
-          repo: saltyorg/sb-go
+          repo: KakatkarAkshay/sb-go
           tag: latest
           extension-matching: disable
           platform: linux
@@ -77,7 +77,12 @@ jobs:
 
       - name: Check sb version
         run: |
-          sudo mv /opt/hostedtoolcache/saltyorg/sb-go/latest/linux-amd64/sb /usr/local/bin/sb
+          SB_BINARY="$(find /opt/hostedtoolcache -path '*/sb-go/latest/*/sb' -type f | head -n 1)"
+          if [ -z "$SB_BINARY" ]; then
+            echo "Unable to locate installed sb binary" >&2
+            exit 1
+          fi
+          sudo mv "$SB_BINARY" /usr/local/bin/sb
           /usr/local/bin/sb version
 
       - name: Create Directories
